#!/bin/bash

# Name of the tmux session
SESSION_NAME="my_session"

# Start a new tmux session named 'my_session'
tmux new-session -d -s $SESSION_NAME

# Split the window vertically
tmux split-window -h

# In the first pane, run 'source venv/bin/activate'
tmux send-keys -t $SESSION_NAME:0.0 'source venv/bin/activate' C-m

# In the second pane, run 'source venv/bin/activate'
tmux send-keys -t $SESSION_NAME:0.1 'source venv/bin/activate' C-m

# Attach to the session
tmux attach -t $SESSION_NAME

# Select the first pane to keep the focus there
tmux select-pane -t $SESSION_NAME:0.0
